# Data cleaning jupyter notebook

In the following notebook, the process of cleaning and sorting the data from the udacity self driving car dataset 2 is shown. The dataset is composed of images from driving in Mountain View California and the corresponding csv file containing the information regarding the labelling.

In [5]:
import pandas as pd
import numpy as np
import cv2
from PIL import Image

In [6]:
df = pd.read_csv('labels.csv')

In [7]:
df.head()

                  filename  xmin  ymin  xmax  ymax       class
0  1478019952686311006.jpg   950   574  1004   620         car
1  1478019952686311006.jpg  1748   482  1818   744  pedestrian
2  1478019953180167674.jpg   872   586   926   632         car
3  1478019953689774621.jpg   686   566   728   618       truck
4  1478019953689774621.jpg   716   578   764   622         car

In [8]:
len(df)

93086

In [9]:
df['class'].value_counts()

car             60788
trafficLight    17253
pedestrian       9866
truck            3503
biker            1676
Name: class, dtype: int64

In [10]:
grouped = df.groupby('class')

In [11]:
biker_group = grouped.get_group('biker')

In [12]:
biker_group.head()

                    filename  xmin  ymin  xmax  ymax  class
159  1478019971686116476.jpg   584   568   638   606  biker
166  1478019971686116476.jpg   858   542   908   602  biker
169  1478019972180014279.jpg   498   570   552   608  biker
181  1478019972685986697.jpg   418   566   470   610  biker
194  1478019973185520968.jpg   332   564   388   612  biker

In [13]:
biker_group['filename'].nunique()

1076

In [14]:
len(biker_group), len(biker_group['filename'].unique().tolist())

(1676, 1076)

In [15]:
biker_filenames = biker_group['filename'].unique().tolist()

In [16]:
new_df = df.loc[df['filename'].isin(biker_filenames)]

In [17]:
new_df['filename'].nunique()

1076

In [18]:
new_df['class'].value_counts()

car             4440
trafficLight    2522
pedestrian      1811
biker           1676
truck            338
Name: class, dtype: int64

In [19]:
truck_group = grouped.get_group('truck')

In [20]:
truck_group.head()

                   filename  xmin  ymin  xmax  ymax  class
3   1478019953689774621.jpg   686   566   728   618  truck
8   1478019954186238236.jpg   662   562   710   616  truck
13  1478019954685370994.jpg   640   560   694   614  truck
17  1478019955185244088.jpg   618   558   678   614  truck
22  1478019955679801306.jpg   598   554   664   612  truck

In [21]:
len(truck_group)

3503

In [22]:
truck_group['filename'].nunique()

2439

In [23]:
truck_filenames = truck_group['filename'].unique().tolist()

In [24]:
truck_df = df.loc[df['filename'].isin(truck_filenames)]

In [25]:
truck_df['filename'].nunique()

2439

In [26]:
final_df = pd.concat([new_df, truck_df])

In [27]:
len(df)

93086

In [28]:
final_df.drop_duplicates()

                      filename  xmin  ymin  xmax  ymax         class
158    1478019971686116476.jpg   546   516   568   550  trafficLight
159    1478019971686116476.jpg   584   568   638   606         biker
160    1478019971686116476.jpg   664   562   750   630           car
161    1478019971686116476.jpg   740   466   758   502  trafficLight
162    1478019971686116476.jpg   746   556   800   600           car
163    1478019971686116476.jpg   752   562   798   592           car
164    1478019971686116476.jpg   816   460   836   494  trafficLight
165    1478019971686116476.jpg   818   456   842   494  trafficLight
166    1478019971686116476.jpg   858   542   908   602         biker
167    1478019971686116476.jpg   966   478   998   518  trafficLight
168    1478019971686116476.jpg  1060   542  1224   596           car
169    1478019972180014279.jpg   498   570   552   608         biker
170    1478019972180014279.jpg   528   512   550   546  trafficLight
171    1478019972180014279.jpg   652   560   738   628           car
172    1478019972180014279.jpg   728   460   746   496  trafficLight
173    1478019972180014279.jpg   736   560   790   604           car
174    1478019972180014279.jpg   740   558   786   588           car
175    1478019972180014279.jpg   810   452   830   486  trafficLight
176    1478019972180014279.jpg   812   448   836   486  trafficLight
177    1478019972180014279.jpg   970   474  1002   514  trafficLight
178    1478019972180014279.jpg  1072   532  1200   598           car
179    1478019972180014279.jpg  1100   548  1134   640    pedestrian
180    1478019972685986697.jpg   138   576   262   628           car
181    1478019972685986697.jpg   418   566   470   610         biker
182    1478019972685986697.jpg   500   506   522   540  trafficLight
183    1478019972685986697.jpg   648   558   736   628           car
184    1478019972685986697.jpg   716   456   734   492  trafficLight
185    1478019972685986697.jpg   722   560   790   602           car
186    1478019972685986697.jpg   728   556   774   586           car
187    1478019972685986697.jpg   804   442   828   480  trafficLight
...                        ...   ...   ...   ...   ...           ...
93029  1478901532389636298.jpg   946   590  1078   674           car
93030  1478901532389636298.jpg   952   578  1068   676           car
93031  1478901532389636298.jpg  1052   558  1282   738           car
93032  1478901532389636298.jpg  1252   470  1914  1098           car
93033  1478901532960567187.jpg    90   608   280   690           car
93034  1478901532960567187.jpg   166   560   412   770         truck
93035  1478901532960567187.jpg   464   622   588   712           car
93036  1478901532960567187.jpg   476   632   580   692           car
93037  1478901532960567187.jpg   580   630   616   686           car
93038  1478901532960567187.jpg   970   598  1098   694           car
93039  1478901532960567187.jpg  1000   606  1084   680           car
93040  1478901532960567187.jpg  1112   560  1426   780           car
93041  1478901533532725411.jpg     0   556   338   778         truck
93042  1478901533532725411.jpg     0   612   190   698           car
93043  1478901533532725411.jpg   424   610   568   710           car
93044  1478901533532725411.jpg   428   612   556   710           car
93045  1478901533532725411.jpg   544   606   604   692           car
93046  1478901533532725411.jpg  1000   594  1140   694           car
93047  1478901533532725411.jpg  1004   584  1128   696           car
93048  1478901533532725411.jpg  1208   534  1628   836           car
93049  1478901534103903218.jpg     0   542   278   826         truck
93050  1478901534103903218.jpg    60   606   274   694           car
93051  1478901534103903218.jpg   166   598   340   696           car
93052  1478901534103903218.jpg   384   608   544   724           car
93053  1478901534103903218.jpg   396   628   546   712           car
93054  1478901534103903218.jpg   482   608   596   700           car
93055  1478901534103903218.jpg   530   620   590   688           car
93056  1478901534103903218.jpg  1026   590  1172   694           car
93057  1478901534103903218.jpg  1032   586  1184   708           car
93058  1478901534103903218.jpg  1352   498  1916   942           car

[30283 rows x 6 columns]

In [29]:
final_df['filename'].nunique()

3303

In [30]:
final_df['class'].value_counts()

car             17200
trafficLight     6358
truck            3841
pedestrian       3732
biker            1997
Name: class, dtype: int64

In [31]:
final_df['xdif'] = final_df['xmax'] - final_df['xmin']

In [32]:
final_df.head()

                    filename  xmin  ymin  xmax  ymax         class  xdif
158  1478019971686116476.jpg   546   516   568   550  trafficLight    22
159  1478019971686116476.jpg   584   568   638   606         biker    54
160  1478019971686116476.jpg   664   562   750   630           car    86
161  1478019971686116476.jpg   740   466   758   502  trafficLight    18
162  1478019971686116476.jpg   746   556   800   600           car    54

In [33]:
final_df = final_df.sort_values(by=['class', 'xdif'])

In [34]:
final_df = final_df.reset_index(drop=True)

In [35]:
final_df

                      filename  xmin  ymin  xmax  ymax  class  xdif
0      1478898931878839067.jpg   288   604   304   646  biker    16
1      1478900648604965875.jpg     0   580    16   666  biker    16
2      1478898666228903545.jpg   590   610   608   650  biker    18
3      1478898666800134931.jpg   560   586   578   626  biker    18
4      1478898667371299966.jpg   544   602   562   640  biker    18
5      1478897854426424817.jpg   148   604   168   686  biker    20
6      1478897854997589082.jpg   148   604   168   686  biker    20
7      1478897855568054263.jpg   148   604   168   686  biker    20
8      1478897856140609864.jpg   148   604   168   686  biker    20
9      1478897856711123471.jpg   148   604   168   686  biker    20
10     1478897857282331271.jpg   148   604   168   686  biker    20
11     1478897858996349508.jpg   148   604   168   686  biker    20
12     1478897859568406026.jpg   148   604   168   686  biker    20
13     1478897860138703556.jpg   146   604   166   686  biker    20
14     1478897860710599728.jpg   146   604   166   686  biker    20
15     1478897861281417115.jpg   146   604   166   686  biker    20
16     1478897861853325897.jpg   146   604   166   686  biker    20
17     1478897862425048693.jpg   144   604   164   686  biker    20
18     1478897862995697054.jpg   144   604   164   686  biker    20
19     1478897863567171969.jpg   144   604   164   686  biker    20
20     1478897864137301612.jpg   144   604   164   686  biker    20
21     1478897864709031648.jpg   144   604   164   686  biker    20
22     1478898247473524587.jpg   696   612   716   664  biker    20
23     1478901198756565702.jpg   838   614   858   660  biker    20
24     1478897854426424817.jpg   148   604   168   686  biker    20
25     1478897854997589082.jpg   148   604   168   686  biker    20
26     1478897855568054263.jpg   148   604   168   686  biker    20
27     1478897856140609864.jpg   148   604   168   686  biker    20
28     1478897856711123471.jpg   148   604   168   686  biker    20
29     1478897857282331271.jpg   148   604   168   686  biker    20
...                        ...   ...   ...   ...   ...    ...   ...
33098  1478900296690150074.jpg   530   464  1890   860  truck  1360
33099  1478900286406433919.jpg   556   400  1918   918  truck  1362
33100  1478900286977653438.jpg   554   408  1916   912  truck  1362
33101  1478900287549257066.jpg   552   416  1914   906  truck  1362
33102  1478900288119887983.jpg   552   424  1914   902  truck  1362
33103  1478900288691527158.jpg   552   432  1914   896  truck  1362
33104  1478900289263467136.jpg   550   440  1912   892  truck  1362
33105  1478900289833970150.jpg   550   448  1912   886  truck  1362
33106  1478900290405858820.jpg   550   458  1912   882  truck  1362
33107  1478900292118820181.jpg   532   484  1894   842  truck  1362
33108  1478900277266607271.jpg   526   434  1912   800  truck  1386
33109  1478900284692849557.jpg   520   408  1918   926  truck  1398
33110  1478900285263820986.jpg   520   408  1918   926  truck  1398
33111  1478900285835600437.jpg   520   408  1918   926  truck  1398
33112  1478900277836512635.jpg   492   434  1910   800  truck  1418
33113  1478900284121101460.jpg   494   398  1918   916  truck  1424
33114  1478900297260681643.jpg   472   472  1918   866  truck  1446
33115  1478900283550490710.jpg   468   390  1918   908  truck  1450
33116  1478900278408788678.jpg   460   440  1912   798  truck  1452
33117  1478900280692890780.jpg   448   442  1910   794  truck  1462
33118  1478900280122842159.jpg   446   448  1910   796  truck  1464
33119  1478900279550831108.jpg   444   450  1910   796  truck  1466
33120  1478900278979584035.jpg   442   442  1912   796  truck  1470
33121  1478899635136732569.jpg   442   198  1918   854  truck  1476
33122  1478900282978670563.jpg   442   382  1918   900  truck  1476
33123  1478900282407133067.jpg   428   372  1918   890  truck  1490
33124  1478900281264617630.jpg   422   400  1914   836  truck  1492
33125  1478900281837465135.jpg   398   360  1918   878  truck  1520
33126  1478896398779330549.jpg     0   176  1664   888  truck  1664
33127  1478899634564672538.jpg     0   236  1712   896  truck  1712

[33128 rows x 7 columns]

In [36]:
final_df['class'].ne('car').idxmin()

1997

In [37]:
final_df.iloc[[1997]]

                     filename  xmin  ymin  xmax  ymax class  xdif
1997  1478899047851282737.jpg   882   590   898   626   car    16

In [38]:
final_df = final_df.drop(final_df.index[1997:11997])

In [39]:
final_df['filename'].nunique()

3303

In [40]:
final_df['class'].value_counts()

car             7200
trafficLight    6358
truck           3841
pedestrian      3732
biker           1997
Name: class, dtype: int64

In [41]:
# def draw_boxes(image_name):
#     selected_value = df[df.filename == image_name]
#     img = cv2.imread('images/{}'.format(image_name))
#     img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#     for index, row in selected_value.iterrows():
#         img = cv2.rectangle(img, (row['xmin'], row['ymin']), (row['xmax'], row['ymax']), (0, 255, 0), 3)
#     return img

In [42]:
# sample_images = final_df.sample(n=20).drop_duplicates(subset='filename')['filename'].tolist()

In [43]:
# Image.fromarray(draw_boxes(sample_images[0]))

In [44]:
filename_grouped = final_df.groupby('filename')

In [45]:
len(filename_grouped)

3303

In [46]:
grouped_list = [filename_grouped.get_group(x) for x in filename_grouped.groups]

In [47]:
train_index = np.random.choice(len(filename_grouped), size=2642, replace=False)
test_index = np.setdiff1d(list(range(3303)), train_index)

In [48]:
len(train_index), len(test_index)

(2642, 661)

In [49]:
train = pd.concat([grouped_list[i] for i in train_index])
test = pd.concat([grouped_list[i] for i in test_index])

In [50]:
len(train), len(test)

(18520, 4608)

In [52]:
len(final_df)

23128

In [ ]:
train.to_csv('data/labels/train_labels.csv', index=None)
test.to_csv('data/labels/test_labels.csv', index=None)